export default {
  browser_dapp: require('../img/public/browser_dapp.png'),
  bottom_log:require('../img/public/bottom_log.png'),
  copy_h:require('../img/public/copy_h.png'),
  close_circle_write:require('../img/public/close_circle_write.png'),
  check: require('../img/public/check.png'),
  coins_drag: require('../img/public/coins_drag.png'),
  coins_delete: require('../img/public/coins_delete.png'),
  copy_dapp: require('../img/public/copy_dapp.png'),
  defaultDapp: require('../img/public/defaultDapp.png'),
  dapp_set:require('../img/public/dapp_set.png'),
  fingerprint: require('../img/public/fingerprint.png'),
  
  Magnifier_ash: require('../img/public/Magnifier_ash.png'),
  reveal_h_pwd: require('../img/public/reveal_h_pwd.png'),
  reveal_pwd: require('../img/public/reveal_pwd.png'),
  refresh_dapp:require('../img/public/refresh_dapp.png'),
  refresh: require('../img/public/refresh.png'),
  share_wx:require('../img/public/share_wx.png'),
  share_pyq:require('../img/public/share_pyq.png'),
  share_qq:require('../img/public/share_qq.png'),
  share_app:require('../img/public/share_app.png'),
  share_dapp: require('../img/public/share_dapp.png'),
  uncheck: require('../img/public/uncheck.png'),
  xin_qr: require('../img/public/xin_qr.png'),

  atmosphere: require('../img/public/atmosphere.png'),
  onAgree: require('../img/public/on.png'),
  offAgree: require('../img/public/off.png'),

  rulesbg: require('../img/public/rulesbg.png'),
  title_icon: require('../img/public/title_icon.png'),
  // rulesintroduction: require('../img/public/rulesintroduction.png'),
  // rules1: require('../img/public/rules1.png'),
  // rules2: require('../img/public/rules2.png'),
  // rules3: require('../img/public/rules3.png'),
  // rules4: require('../img/public/rules4.png'),
  // rules51: require('../img/public/rules51.png'),
  // rules52: require('../img/public/rules52.png'),
  // rules6: require('../img/public/rules6.png'),

  //tab图标
  tab_1: require('../img/public/tab_1.png'),
  tab_2: require('../img/public/tab_2.png'),
  tab_3: require('../img/public/tab_3.png'),
  tab_4: require('../img/public/tab_4.png'),
  tab_1_h: require('../img/public/tab_1_h.png'),
  tab_2_h: require('../img/public/tab_2_h.png'),
  tab_3_h: require('../img/public/tab_3_h.png'),
  tab_4_h: require('../img/public/tab_4_h.png'),

  //首页图标
  homeBannerBg: require('../img/home/homeBannerBg.png'),
  team_bg: require('../img/home/team_bg.png'),
  bronze: require('../img/home/bronze.png'),
  bronze_light: require('../img/home/bronze-light.png'),
  silver: require('../img/home/silver.png'),
  silver_light: require('../img/home/silver-light.png'),
  gold: require('../img/home/gold.png'),
  gold_light: require('../img/home/gold-light.png'),
  diamond: require('../img/home/diamond.png'),
  diamond_light: require('../img/home/diamond-light.png'),


  //设置图标
  set_bg: require('../img/set/set_bg.png'),
  set_eye: require('../img/set/set_eye.png'),
  set_logo: require('../img/set/set_logo.png'),
  set_logoA: require('../img/set/set_logoA.png'),
  set_logoB: require('../img/set/set_logoB.png'),
  set_logoC: require('../img/set/set_logoC.png'),
  set_talk: require('../img/set/set_talk.png'),
  set_information: require('../img/set/set_information.png'),
  set_about: require('../img/set/set_about.png'),
  share_card: require('../img/set/share_card.png'),
  min_logo: require('../img/set/min_logo.png'),
  integral_bg: require('../img/set/integral_bg.png'),
  noRecord: require('../img/set/noRecord.png'),
  icon_hsn: require('../img/set/icon_hsn.png'),
  icon_usdt: require('../img/set/icon_usdt.png'),
  rule_whole: require('../img/set/rule_whole.png'),
  icon_add: require('../img/nodesq/add.png'),
  icon_reduce: require('../img/nodesq/reduce.png'),
  hsn_bluelog: require('../img/set/hsn_bluelog.png'),

  blue_logo: require('../img/set/blue_logo.png'),
  blue_logoa: require('../img/set/blue_logoa.png'),
  icon_scret: require('../img/set/icon_scret.png'),
  icon_profile: require('../img/set/profile.png'),

//  登录图标
  login_bg_blue: require('../img/login/logo_blue.png'),
  forgetIcon: require('../img/login/forget_icon.png'), 

//  我的邀请
  rulesTips: require('../img/invite/rules_tips.png'),
  shareIcon: require('../img/invite/icon_share.png'),
  rule_Invitation: require('../img/invite/rule_Invitation.png'),
  share_bg: require('../img/invite/share_bg.png'),

//  节点申请
  jd_bg: require('../img/nodesq/node_bg.png'),
  icon_clock: require('../img/nodesq/icon_point_time.png'),
  confirm_bg: require('../img/nodesq/confirm_bg.png'),
  fireworks: require('../img/nodesq/fireworks.png'),
  icon_lock: require('../img/nodesq/lock_icon.png'),
  sad_face: require('../img/nodesq/sad_face.png'),

  guard_bronze: require('../img/nodesq/guard_bronze.png'),
  guard_silver: require('../img/nodesq/guard_silver.png'),
  guard_gold: require('../img/nodesq/guard_gold.png'),
  guard_diamond: require('../img/nodesq/guard_diamond.png'),
 
  notactive: require('../img/public/notactive.png'),
  early: require('../img/public/early.png'),
  in: require('../img/public/in.png'),
  high: require('../img/public/high.png'),
  super: require('../img/public/super.png'),
  contacts: require('../img/public/contacts.png'),
  icon_refresh: require('../img/public/icon_refresh.png'),
}
